name: TownyDeath
version: ${project.version}
main: me.jaimemartz.townydeath.TownyDeath
authors: [jaime29010]
depend: [Towny, Vault]
softdepend: [HAC]
commands:
  townydeath:
    description: 'Spawn a banner'
    permission: townydeath.admin
  spawn:
    description: 'Go to the spawn'